apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stock-management.fullname" . }}-db-secret
  labels:
    {{- include "stock-management.database.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgresql.auth.username | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password | b64enc | quote }}
  POSTGRES_DB: {{ .Values.postgresql.auth.database | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stock-management.fullname" . }}-backend-secret
  labels:
    {{- include "stock-management.backend.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_URL: {{ printf "postgresql://%s:%s@%s-postgresql:%d/%s?schema=public" .Values.postgresql.auth.username .Values.postgresql.auth.password (include "stock-management.fullname" .) (.Values.postgresql.service.port | int) .Values.postgresql.auth.database | b64enc | quote }}
